### ISSUE TITLE
运行结果没有out文件

### ISSUE THREAD

**Issue by zyzhang827** [misa-kmc/misa-akmc#2]
![](https://s3.bmp.ovh/imgs/2022/03/77d18af8e0d40eb7.png)

我按照示例运行之后，并没有任何的`.out`文件输出，终端只是显示这样的结果，
请问，这是什么原因呢？该如何解决？

**Comment by zyzhang827** [comment]
@genshen

**Comment by genshen** [comment]
应该可以用 [dev](https://github.com/misa-kmc/misa-akmc/commit/186e800b5df15babe089e354b436f0778f9d18b3) 分支的代码，dev 分支的有输出文件的功能。
依赖代码包下载 https://osdn.net/rel/misa-kmc/pkg-dependencies/dev-commit-186e800。

**Comment by zyzhang827** [comment]
好的，根据您的提示，已经正常输出了。

感谢您的回答。
