### ISSUE TITLE
Some errors occurred while installing the dependency

### ISSUE THREAD

**Issue by mudanyancai** [misa-kmc/misa-akmc#3]
Hello, I encountered some problems when building MISA-KMC. I tried to use the third method to import dependencies and build MISA-KMC, but the following error message appeared:

> CMake Error at dependency.cmake:33 (include):
> 
>   include could not find requested file:
> 
>     pkg.dep.cmake
> Call Stack (most recent call first):
>   CMakeLists.txt:9 (include)

Then, I changed to the second way of importing dependencies and tried to install dependencies and build the program. I can't get some dependencies normally by using fetch instruction. I tried to INSTALL the imported dependency using the install directive, but it got an error. The error message is as follows: 

> INFO[0000] installing package.                           pkg=github.com/Taywee/args
> INFO[0000] package built and installed.                  pkg=github.com/Taywee/args
> INFO[0000] installing package.                           pkg=github.com/jbeder/yaml-cpp
> INFO[0238] package built and installed.                  pkg=github.com/jbeder/yaml-cpp
> INFO[0238] installing package.                           pkg=github.com/google/googletest
> INFO[0261] package built and installed.                  pkg=github.com/google/googletest
> INFO[0261] installing package.                           pkg=github.com/fmtlib/fmt
> INFO[0278] package built and installed.                  pkg=github.com/fmtlib/fmt
> INFO[0278] installing package.                           pkg=git.hpcer.dev/genshen/kiwi
> FATA[0281] exit status 1
                                
I'm not sure what caused the error, so I submitted issues for help. 
tips：I tried to visit KIWI's website, but failed. 

我试了第一种，第二种和第三种导入依赖安装的方法，第一种下载依赖的时候报错，第二种用fetch命令的时候报错，第三种显示缺少文件。请问该怎么做才能正确的安装MISA-KMC？希望您能看到这个疑惑，真的有些不知道该怎么做了。

**Comment by genshen** [comment]
It seems that there was a compiling error when building the kiwi library. I need to review the compiling log. Please use the command 'pkg install -- verbose' to show it and seed it to me.   
看来是 kiwi 库的编译出错了。我需要看下详细的日志，用命令 `pkg install --verbose` 查看即可。

**Comment by mudanyancai** [comment]
我把输出信息保存在1.txt的文本文件中。
[1.txt](https://github.com/user-attachments/files/15780881/1.txt)
这是其中kiwi库的一部分：

> time="2024-06-11T09:24:20+08:00" level=info msg="installing package." pkg=git.hpcer.dev/genshen/kiwi
> time="2024-06-11T09:24:20+08:00" level=info msg="running [ cmake -S \"/home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0\" -B \"/home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/cache/git.hpcer.dev/genshen/kiwi\" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=\"/home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/pkg/git.hpcer.dev/genshen/kiwi\"  ] in directory  /home/lammps/soft/kmc/misa-kmc/misa-akmc-master"
> -- MPI_INCLUDE dir:/opt/mpich3.3.2/include
> -- MPI_LIBRARIES dir:/opt/mpich3.3.2/lib/libmpicxx.so/opt/mpich3.3.2/lib/libmpi.so
> -- Could NOT find GTest (missing: GTest_DIR)
> -- Could NOT find fmt (missing: fmt_DIR)
> CMake Error at src/CMakeLists.txt:44 (get_target_property):
>   get_target_property() called with non-existent target "fmt::fmt".
> 
> 
> -- TEST is enabled
> -- MPI in test:
> -- Configuring incomplete, errors occurred!
> time="2024-06-11T09:24:21+08:00" level=fatal msg="exit status 1"

这个是缺少什么吗，似乎提示无法找到两个对应的文件夹？

**Comment by genshen** [comment]
清除下 vendor/cache 目录，然后重新执行 `pkg fetch`, `pkg install` 命令，看下是否还有错误 。

**Comment by mudanyancai** [comment]
我根据您的建议，删除了vendor/cache下的两个文件夹，重新执行 `pkg fetch`, `pkg install` 命令。
`pkg fetch `命令正常执行：终端显示如下：

> INFO[0000] packages will be downloaded to directory /home/lammps/.pkg/registry/default-pkg/src 
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/google/googletest src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/google/googletest@release-1.10.0
> INFO[0000] skipped fetching package, because it already exists.  pkg=git.hpcer.dev/genshen/kiwi src_path=/home/lammps/.pkg/registry/default-pkg/src/git.hpcer.dev/genshen/kiwi@v0.3.0
> INFO[0000] skipped fetching package, because it already exists.  pkg=git.hpcer.dev/HPCer/CrystalMD/libcomm src_path=/home/lammps/.pkg/registry/default-pkg/src/git.hpcer.dev/HPCer/CrystalMD/libcomm@v0.3.3
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/misa-kmc/xoshiro src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/misa-kmc/xoshiro@v0.1.1
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/Taywee/args@6.2.2@args src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/Taywee/args@6.2.2
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/jbeder/yaml-cpp@yaml-cpp-0.6.2@yaml-cpp src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/jbeder/yaml-cpp@yaml-cpp-0.6.2
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/google/googletest src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/google/googletest@release-1.10.0
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/fmtlib/fmt src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/fmtlib/fmt@6.1.2
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/google/googletest src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/google/googletest@release-1.10.0
> INFO[0000] skipped fetching package, because it already exists.  pkg=github.com/google/googletest src_path=/home/lammps/.pkg/registry/default-pkg/src/github.com/google/googletest@release-1.10.0
> INFO[0000] saved dependencies tree to file.              file=vendor/pkg.sum.yaml
> INFO[0000] fetch succeeded. 

`pkg install `命令仍出现错误：

> INFO[0000] installing package.                           pkg=github.com/google/googletest
> INFO[0009] package built and installed.                  pkg=github.com/google/googletest
> INFO[0009] installing package.                           pkg=github.com/fmtlib/fmt
> INFO[0016] package built and installed.                  pkg=github.com/fmtlib/fmt
> INFO[0016] installing package.                           pkg=git.hpcer.dev/genshen/kiwi
> FATA[0017] exit status 2                                

然后尝试删除vendor文件夹，执行了`pkg import`， `pkg fetch`与`pkg install` 三个命令，依旧是`pkg install` 命令报错，以下为开始出现错误的信息：

> /home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0/src/config/../utils/bundle.h:77:29: 错误：‘vector’ in namespace ‘std’ does not name a template type
>          void put(const std::vector<T> &data);
>                              ^~~~~~
> /home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0/src/config/../utils/bundle.h:77:24: 附注：‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
> /home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0/src/config/../utils/bundle.h:11:1:
> +#include <vector>
> 
> /home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0/src/config/../utils/bundle.h:77:24:
>          void put(const std::vector<T> &data);
>                         ^~~
> /home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0/src/config/../utils/bundle.h:77:35: 错误：expected ‘,’ or ‘...’ before ‘<’ token
>          void put(const std::vector<T> &data);
>                                    ^
> /home/lammps/soft/kmc/misa-kmc/misa-akmc-master/vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0/src/config/../utils/bundle.h:92:36: 错误：‘std::vector’尚未声明
>          void get(int &cursor, std::vector<T> &data);
>                                     ^~~~~~

完整的日志在文件 ‘3.txt’ 中，希望能让您了解这个问题的原因，谢谢您的帮助。
[3.txt](https://github.com/user-attachments/files/15789109/3.txt)

**Comment by genshen** [comment]
Maybe you should add `#include <vector>` at the header of file `vendor/src/git.hpcer.dev/genshen/kiwi@v0.3.0/src/config/../utils/bundle.h`. 
This is a known bug of kiwi v0.3.0 (see https://github.com/genshen/kiwi/commit/c4db6d8c798ce6cef05635c63f6c75536419ee99).  

If compiling issues still occurs, please seed me an email for quick reply.

**Comment by mudanyancai** [comment]
非常感谢您的帮助，参考链接对应的页面对文件修改后，已经正常安装并测试了。
